# JrGames小游戏主插件配置

# 主城所在的世界名
lobby: 'world'

# 游戏开始倒计时tick (1秒20tick),记得加上1秒
startCountDownTicks: 420

# 调试模式
debug: true

# MOTD
# 显示样板:
# 名称 - 简介 | 更多1
# 群 | 更多2
motd:
  # 名称
  name: 'JRGames'
  # 介绍
  description: 'JMC小游戏周目'
  # 更多1
  more1: '期待您的到来'
  # 群
  qun: 'QQ群 799512425'
  # 更多2
  more2: '请从 mc.hjfunny.site 进入'

# snow fight配置
snowFight:
  # 地图
  map: 'snow_fight'
  # 最少人数
  minPlayers: 1
  # 最多人数
  maxPlayers: 114
  # 游玩时间,tick,记得加上1秒
  playTime: 2420
  # 游戏开始坐标
  spawnX: 0
  spawnY: 31
  spawnZ: 0