# JrGames小游戏主插件配置

# 主城所在的世界名
lobby: 'world'

# 游戏开始倒计时tick (1秒20tick),记得加上1秒
startCountDownTicks: 420

# 调试模式
debug: true

# snow fight配置
snowFight:
  # 地图
  map: 'snow_fight'
  # 最少人数
  minPlayers: 1
  # 最多人数
  maxPlayers: 114
  # 游玩时间,tick,记得加上1秒
  playTime: 2420
  # 游戏开始坐标
  spawnX: 0
  spawnY: 20
  spawnZ: 0