name: Jrgames
version: '${project.version}'
main: cn.jerrymc.jrgames.Jrgames
api-version: 1.17
depend: [ PlaceholderAPI, Vault, ItemsAdder, Multiverse-Core ]
authors: [ bcmray ]
commands:
  jstopall:
    description: 强制停止所有游戏
    usage: /jstopall